eventName:
  Первенство Пятой Бани

eventDate:
  20.02.2022

eventSport:
  orienteering


ranks:
  - 3ю
  - 2ю
  - 1ю
  - 3р
  - 2р
  - 1р
  - КМС
  - МС


groups:
  - group: М10
    distance: МЖ9 10
  - group: М12
    distance: М12
  - group: М14
    distance: М14
  - group: М16
    distance: М16 Ж60
  - group: М18
    distance: М18 21 40 50
  - group: М21
    distance: М18 21 40 50
  - group: М40
    distance: М18 21 40 50
  - group: М60
    distance: Ж21 40 М60
  - group: Ж10
    distance: МЖ9 10
  - group: Ж12
    distance: Ж12
  - group: Ж14
    distance: Ж14
  - group: Ж16
    distance: Ж16
  - group: Ж18
    distance: Ж21 40 М60
  - group: Ж21
    distance: Ж21 40 М60
  - group: Ж40
    distance: Ж21 40 М60
  - group: Ж60
    distance: М16 Ж60
  - group: Мстуд
    distance: Ж16 студенты
  - group: Жстуд
    distance: Ж16 студенты
  - group: VIP
    distance: МЖ9 10


criteria:
  - distance: М18 21 40 50
    checkpoints:
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 39
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 49
    - 52
    - 53
  - distance: МЖ9 10
    checkpoints:
    - 32
    - 46
    - 34
    - 33
    - 53
  - distance: Ж14
    checkpoints:
    - 47
    - 46
    - 45
    - 34
    - 33
    - 32
    - 48
    - 52
    - 51
    - 50
    - 49
    - 53
  - distance: Ж12
    checkpoints:
    - 32
    - 46
    - 33
    - 47
    - 48
    - 52
    - 51
    - 50
    - 49
    - 53
  - distance: М12
    checkpoints:
    - 32
    - 46
    - 34
    - 35
    - 45
    - 33
    - 47
    - 48
    - 52
    - 49
    - 53
  - distance: М14
    checkpoints:
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 44
    - 45
    - 46
    - 47
    - 48
    - 53
  - distance: Ж21 40 М60
    checkpoints:
    - 33
    - 34
    - 35
    - 36
    - 43
    - 42
    - 39
    - 40
    - 38
    - 37
    - 44
    - 45
    - 46
    - 32
    - 48
    - 49
    - 50
    - 51
    - 49
    - 52
    - 53
  - distance: М16 Ж60
    checkpoints:
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 43
    - 37
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 51
    - 52
    - 53
  - distance: Ж16  студенты
    checkpoints:
    - 32
    - 33
    - 34
    - 44
    - 36
    - 37
    - 35
    - 45
    - 46
    - 47
    - 48
    - 49
    - 52
    - 53
