sport:
  running

groups:
  - М10
  - M12
  - M14
  - M16
  - M18
  - M20
  - W10
  - W12
  - W14
  - W16
  - W18
  - W20

ranks:
  - б/р
  - 3ю
  - 2ю
  - 1ю
  - 3
  - 2
  - 1
  - КМС
  - МС
  - ЗМС
  - ЗМСМК